name: deploy
run-name: deploying model for ${{ github.actor }}
on: [push]
jobs:
  Super-Resolution:
      runs-on: self-hosted
      steps:
        - name: cache dependencies
          id: cache-dependencies
          uses: actions/cache@v3
        - name: transformation
          run: python super_resolve.py
