name: deploy
run-name: deploying model for ${{ github.actor }}
on: [push]
jobs:
  Super-Resolution:
      runs-on: self-hosted
      steps:
        - name: transformation
          run: python "C:\Users\n.strokova\Downloads\super-resolution-master (3)\super-resolution-master\super_resolve.py"
