name: deploy
run-name: deploying model for ${{ github.actor }}
on: [push]
jobs:
  deploy-linear-svm:
      runs-on: self-hosted
      steps:
        - name: cache dependencies
          id: cache-dependencies
          uses: actions/cache@v3
          with:
            path: /home/runner/work/_temp/Library
            key:  dependencies-v4

        - name: checkout repo
          uses: actions/checkout@master  # cwd: /home/runner/work/ahri/ahri

        - name: cache embeddings
          id: cache-embeddings
          uses: actions/cache@v3
          with:
            path: assets/pmi-word-vectors.csv
            key: embeddings

        - name: setup r environment
          uses: r-lib/actions/setup-r@v2

        - name: pull trained model
          uses: actions/download-artifact@v3
          with:
            name: trained-linear-svm
            path: assets/models

        - name: deploy linear svm classifier
          if: ${{ false }}  # set to true to enable an actual deployment which will suspend the runner
          run: ./ahri/rest.r -v assets/pmi-word-vectors.csv -m assets/models/weights.svmLinear.rds
