name: GigaChat
on: [workflow_dispatch]
jobs:
  SubPixelCNN:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.6"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install numpy
          pip install yadisk
          pip install torch
          pip install torchvision
          pip install Pillow
          pip install six
          pip install PuzzleLib

      - name: Train model and save result
        working-directory: ./Models
        run: python main.py -m sub

      - name: Configure Git
        run: |
          git config --global user.name 'stnastyast'
          git config --global user.email 's.anastasia.strokova@gmail.com'

      - name: Add changes
        working-directory: ./Models
        run: git add SUB_model_path.pth

      - name: Commit changes
        working-directory: ./Models
        run: git commit -m "Add trained model weights"

      - name: Push changes
        run: git push origin main
