name: Test
on: [workflow_dispatch]
jobs:
  EDSR_Training:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: install numpy
        run: pip install numpy
      - name: install tensorflow
        run: pip install tensorflow
      - name: install torchvision
        run: pip install torchvision
      - name: training
        env:
          DB_USERNAME: github
          DB_PASSWORD: ${{secrets.DBPASSWORD}}
        #run: python Neural_Network/main.py -m [srcnn]
        run: python3 Neural_Network/main.py -m [sub/srcnn/cdsr/edsr/fsrcnn/drcn/srgan/dbpn]
