name: Test Workflow
on: [workflow_dispatch]
jobs: 
  EDSR_Training:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.6"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.6'        
        
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: install numpy
        run: pip install numpy
      - name: install torch
        run: pip install torch
      - name: install torchvision
        run: pip install torchvision
      - name: install PIL
        run: pip install Pillow
      - name: install six
        run: pip install six
      - name: install PuzzleLib
        run: pip install PuzzleLib
        
      - name: training
        env:
          DB_USERNAME: github
          DB_PASSWORD: ${{secrets.DBPASSWORD}}
        run: python models/test.py
