name: Dataset Workflow
on: [workflow_dispatch]
jobs:
  LoadDataset:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: install kaggle API
        run: pip install kaggle
      - name: download dataset
        env:
          KAGGLE_USERNAME: avstrokova
          KAGGLE_KEY: 5e2c622209c9f22356e8e944eebba69c
        run: kaggle datasets download avstrokova/div2-k-dataset-for-super-resolution
      - name: unpack dataset archive
        run: unzip div2-k-dataset-for-super-resolution.zip

  PreprocessDataset:
    runs-on: ubuntu-latest
    needs: LoadDataset
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: install Pillow
        run: pip install Pillow
      - name: process_data
        env:
          DB_USERNAME: github
          DB_PASSWORD: ${{secrets.DBPASSWORD}}
        run: python datasetpreprocessing.py
