name: Workflow
on: [workflow_dispatch]
jobs:
  LoadDataset:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: install kaggle API
        run: pip install kaggle
      - name: download dataset
        env:
          KAGGLE_USERNAME: avstrokova
          KAGGLE_KEY: ${{secrets.KAGGLEKEY}}
        run: kaggle datasets download chenqizhou/div2k-bicubic-x4
      - name: unpack dataset archive
        run: unzip div2k-bicubic-x4.zip
