name: evaluate
run-name: deploying model for ${{ github.actor }}
on: [push]
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: cache source data
        id: cache-source-data
        uses: actions/cache@v3
        with:
          path: assets/source-data
          key: source-dataset

      # Download dataset
      - name: download source data
        if: steps.cache-source-data.outputs.cache-hit != 'true'
        env:
          KAGGLE_TOKEN: ${{ secrets.KAGGLE_TOKEN }}
        run: |
          pip install kaggle
          mkdir $HOME/.kaggle
          echo $KAGGLE_TOKEN > $HOME/.kaggle/kaggle.json
          kaggle datasets download -d advaypatil/youtube-statistics
          mkdir -p assets/source-data/
          sudo apt-get install unzip
          unzip youtube-statistics.zip -d assets/source-data/
