
name: Dataset Workflow
on: [workflow_dispatch]
jobs:
  LoadDataset:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: install kaggle API
        run: pip install -q kaggle
      - name: mkdir
        run: mkdir ~/.kaggle
      - name: cp
        run: cp super-resolution/pictures/kaggle.json
      - name: chmod
        run: chmod 600 ~/kaggle.json
      - name: download
        run: kaggle datasets download joe1995/div2k-dataset
