name: workflow
run-name: deploying model for ${{ github.actor }}
on: [push]
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: cache source data
        id: cache-source-data
        uses: actions/cache@v3
        with:
          path: assets/source-data
          key: source-dataset

      # Download dataset
      - name: download source data
        if: steps.cache-source-data.outputs.cache-hit != 'true'
        env:
          KAGGLE_TOKEN: ${{ secrets.KAGGLE_TOKEN }}
        run: |

          import tempfile, os, zipfile
          import requests
          response = requests.get('http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_train_LR_bicubic_X2.zip')
          file = tempfile.TemporaryFile()
          file.write(response.content)
          fzip = zipfile.ZipFile(file)
          
          mkdir -p assets/source-data/
          sudo apt-get install unzip
          unzip DIV2K_train_LR_bicubic_X2.zip -d assets/source-data/
